---
title: "Access to Care Analysis"
output: html_notebook
---

```{r, include = FALSE}
library(tidyverse)
library(rlang)
library(leaflet)
library(purrr)
library(tigris)
library(fs)
```

```{r, eval = FALSE}
library(tidyverse)
library(rlang)
library(leaflet)
library(purrr)
library(tigris)
library(fs)
```

https://data.medicare.gov/Hospital-Compare/Structural-Measures-Hospital/4hje-vua3

```{r}
hospitals_raw <- read_csv("../data/Structural_Measures_-_Hospital.csv") # for csv file
#hospitals_raw <- haven::read_sas("../data/Structural_Measures_-_Hospital.sas7bdat") # for SAS file 
``` 

```{r}
hospitals <- hospitals_raw %>%
  rename_all(str_to_lower) %>%
  rename_all(str_replace_all, " ", "_") %>%
  select(provider_id, hospital_name, state, county_name, location) %>%
  group_by_all() %>%
  summarise() %>%
  ungroup() %>%
  separate(location, into = c("address", "location"), sep = "\\(") %>%
  mutate(location = str_remove(location, "\\)")) %>%
  separate(location, into = c("latitude", "longitude"), sep = ",") %>%
  mutate(
    longitude = as.numeric(longitude), latitude = as.numeric(latitude),
    county_key = str_remove_all(county_name, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint"))  

```

```{r}
hospitals
```

```{r}
hospital_locations <- hospitals  %>%
  filter(!is.na(longitude)) %>%
  select(state, longitude, latitude)
write_rds(hospital_locations, "../data/hospital_locations.rds")
hospital_locations
```

```{r}
population <- usmap::countypop %>%
  mutate(
    county_key = str_remove_all(county, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint")) %>%
  rename(
    population = pop_2015,
    state = abbr
    )
population
```


```{r}
hospital_count <- hospitals %>%
  count(state, county_name) %>%
  filter(!is.na(county_name)) %>%
  mutate(
    county_key = str_remove_all(county_name, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st.", "saint")) %>%
  rename(hospitals = n)
hospital_count
```


```{r}
state_hospitals <- population %>%
  left_join(hospital_count, by = c("state" = "state", "county_key" = "county_key")) %>%
  replace_na(list(hospitals = 0)) 
state_hospitals
```

```{r}
set.seed(100)

hospital_sample <- state_hospitals %>%
  sample_frac(0.3)

hospital_sample
```

```{r}
model <- lm(hospitals ~ population, data = hospital_sample)
write_rds(model, "../data/model.rds")
summary(model)
```

```{r}
predictions <- predict(model, 
  newdata = state_hospitals, 
  interval = "prediction") %>%
  as_tibble() %>%
  mutate_all(round)

predictions
```

```{r}
hospital_results <- state_hospitals %>%
  bind_cols(predictions) %>%
  mutate(result = case_when(
    hospitals < lwr ~ -1,
    hospitals > upr ~ 1,
    TRUE ~ 0))
write_rds(hospital_results, "../data/hospitals.rds")

hospital_results 
```

## State map

```{r}
dir_create("shapes")
all_paths <- path("../shapes", state.abb, ext = "rds") %>%
  set_names(state.abb)

exist <- file_exists(all_paths)

county_paths <- all_paths[!exist]

imap(
  county_paths,
  ~ counties(.y) %>%
    write_rds(.x)
)

select_row <- function(x, y) x %% y == 0

extract_coordinates <- function(path, decimals = 2) {
  state_rds <- readRDS(path)
  state_rds@polygons %>%
    map(~ {
      map(
        .x@Polygons,
        ~ tibble(
          long = .x@coords[, 1],
          lat = .x@coords[, 2],
          rn = 1:length(.x@coords[, 1]),
          sel = select_row(rn, 10)
        )) %>% 
        set_names(paste0("s", seq_along(.x@Polygons))) %>%
        map_df(~.x, .id = "shape_id")}) %>%
    set_names(state_rds$NAME) %>%
    map_df(~.x, .id = "county") %>%
    filter(sel) %>%
    select(-rn, -sel)
}

county_states <- map_dfr(
  all_paths,
  extract_coordinates,
  .id = "state"
) 

nested_states <- county_states %>%
  group_nest(state, county, shape_id) %>%
  group_nest(state, county)

write_rds(nested_states, "../data/shapes.rds", compress = "gz")
```


```{r}
shapes <- nested_states %>%
  mutate(
    county_key = str_to_lower(county),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint")
  ) 

shapes 
```

```{r}
county_hospitals <- hospital_results  %>%
  select(- county) %>%
  left_join(shapes, by = c("state", "county_key")) %>%
  #filter(state != "PR", state != "AK") %>%
  filter(!is.na(county))

write_rds(county_hospitals, "../data/county_hospitals.rds", compress = "gz")

county_hospitals
```

```{r}
library(usmap)

state_abbr <- "VA"

under <- "#CC79A7"
over <- "#0072B2"
at_level <- "#008b00"
hospital_color <- "#F0E442"

counties <- county_hospitals %>% 
    filter(state == state_abbr) %>%
    mutate(popup = paste0("<b>", county, "</b>",
                          "<br/>Population: ", prettyNum(population, big.mark = ","), 
                          "<br/>Hospitals: ", hospitals,
                          "<br/>Expected: ", fit
                          )) %>%  
    mutate(color = case_when(
      result ==  0  ~ at_level,
      result ==  1  ~ over,
      result == -1  ~ under
    ))

initial_map <- leaflet() %>%
  addProviderTiles(providers$CartoDB) %>%
  addLegend("bottomright", 
            color  = c(under,over ,at_level, hospital_color), 
            labels = c("Less hopitals than expected",
                       "More hospitals than expected", "Within Range", 
                       "Hospital Location"), 
            title  = "Legend",opacity = 0.5)

county_map <- counties %>%
  transpose() %>%
  map(~{
    county <- .x
     transpose(county$data)  %>%
       map(~list(
         data = .x$data, 
         color = county$color,
         popup = county$popup
         ))
    }) %>%
  flatten() %>%
  reduce(
    ~ addPolygons(.x, 
                  lng = .y$data$long, 
                  lat = .y$data$lat, 
                  color = .y$color, 
                  popup = .y$popup,
                  weight = 1, fillOpacity = 0.3), 
    .init = initial_map)  

locations <- hospital_locations %>%
  inner_join(statepop, by = c("state" = "abbr")) %>%
  filter(state == state_abbr) %>%
  select(longitude, latitude) %>%
  mutate_all(round, 3) %>%
  count(longitude, latitude) %>%
  mutate(popup = paste0("Hospitals: ", n))

county_map <- county_map %>%
  addCircleMarkers(
    lng = locations$longitude, 
    lat = locations$latitude,
    radius = 3 *locations$n,
    popup = locations$popup,
    fillColor = hospital_color, color = "gray", 
    fillOpacity = 0.7,weight = 1)

county_map  
```


```{r}
library(fs)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds", "model.rds")) %>%
  file_copy("../flexdashboard", overwrite = TRUE)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds", "model.rds")) %>%
  file_copy("../presentation", overwrite = TRUE)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../RMarkdown-html", overwrite = TRUE)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../RMarkdown-pdf", overwrite = TRUE)

path("..","data", c("model.rds", "hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../plumber-api", overwrite = TRUE)

path("..","data", c("model.rds", "county_hospitals.rds")) %>%
  file_copy("../powerpoint", overwrite = TRUE)

path("..","data", c("model.rds", "county_hospitals.rds")) %>%
  file_copy("../powerpoint-state", overwrite = TRUE)


```

