---
title: "Access to Care - Dashboard"
format: 
  dashboard:
    theme: custom-theme.scss
    expandable: false
server: shiny
---


```{r}
#| context: setup
library(accesstocare)
library(ggplot2)
library(ggiraph)
library(usmap)
library(dplyr)
library(shiny)
library(gt)
library(bslib)
library(bsicons)

state_list <- c("All US", us_states$state_name)

us_choices <- c("Population", "No. of Hospitals", "Below model", "Above model")
state_choices <- c("Model", "No. of Hospitals", "Population")
```

# State info

## Row {height=20%}

### Column

```{r}
selectInput(
  inputId = "state",
  label = "Select a State:",
  choices = state_list,
  selected = "All US",
  selectize = FALSE
)
```

### Column

```{r}
showcase_vals <- showcase_bottom(height = "50%", max_height = "50%")

value_box(
  title = "Population",
  value = textOutput("population"),
  showcase = bs_icon("person"),
  showcase_layout = showcase_vals
)
```

### Column

```{r}
value_box(
  title = "Hospitals",
  value = textOutput("hospitals"),
  showcase = bs_icon("hospital"),
  showcase_layout = showcase_vals,
  theme = "teal"
)
```

### Column

```{r}
value_box(
  title = "Counties",
  value = textOutput("counties"),
  showcase = bs_icon("geo-alt"),
  showcase_layout = showcase_vals
)
```

### Column

```{r}
value_box(
  title = "Underserved",
  value = textOutput("underserved"),
  showcase = bs_icon("clipboard2-pulse"),
  showcase_layout = showcase_vals
)
```

## Row {height=80%}

### {.sidebar}

```{r}
radioButtons(
  inputId = "view",
  label = p(strong("Select a view:")),
  choices = us_choices,
  inline = TRUE
)

br()

actionButton(
  inputId = "us",
  label = "Reset"
)
hr()
p(em("Sources: Centers of Medicine & Medicaid services (2025), and US Census Bureau (2024)."))
```

### Column


```{r}
girafeOutput("usmap")
```



# Model  {orientation="columns" scrolling="true"}

## Column

::: {.card title="Population vs No. of Hospitals"}

```{r}
girafeOutput("pop_plot")

sliderInput(
  inputId = "pop",
  label = "Population",
  min = 0, max = 11000000,
  value = 11000000,
  step = 1000000,
  width = "700px"
)
```

There was a high degree of correlation between the county's population and the number of hospitals

:::

## Column

::: {.card title="Identifying underserved counties"}

```{r}
girafeOutput("pop_plot_model")
```

Fitted a model to estimate how many hospitals should be in a county

:::


```{r}
#| context: server
#|
sel_state <- reactive({
  if (input$state == "All US") {
    us_states
  } else {
    us_states |>
      filter(state_name == input$state)
  }
})

sel_county <- reactive({
  if (input$state == "All US") {
    us_counties
  } else {
    us_counties |>
      filter(state_name == input$state)
  }
})

output$population <- renderText({
  sel_state() |>
    summarise(sum(population)) |>
    pull() |>
    format_number()
})


output$hospitals <- renderText({
  sel_state() |>
    summarise(sum(hospitals)) |>
    pull() |>
    format_number()
})

output$counties <- renderText({
  sel_county() |>
    count() |>
    pull() |>
    format_number()
})

output$underserved <- renderText({
  sel_county() |>
    filter(pred_status == "below") |>
    count() |>
    pull()
})

output$usmap <- renderGirafe({
  y_size <- 5
  vr <- "population"
  if (input$view == "Population") vr <- "population"
  if (input$view == "No. of Hospitals") vr <- "hospitals"
  if (input$view == "Above model") vr <- "above"
  if (input$view == "Below model") vr <- "below"
  if (input$view == "Model") vr <- "model"

  if (input$state == "All US") {
    gp <- atc_plot_us_map(vr)
  } else {
    props <- us_atc_county_polygons |>
      filter(state_name == input$state) |>
      summarise(
        max_x = max(x), min_x = min(x),
        max_y = max(y), min_y = min(y)
      ) |>
      mutate(
        x_size = max_x - min_x,
        y_size = max_y - min_y,
        xy = x_size / y_size * 8
      )
    y_size <- props$y_size / props$x_size * 10
    y_size <- ifelse(y_size > 5, 5, y_size)
    gp <- atc_plot_state_map(input$state, vr)
  }

  girafe(
    ggobj = gp,
    height_svg = y_size,
    options = list(
      opts_selection(type = "single", only_shiny = FALSE),
      opts_tooltip(opacity = 0.7),
      opts_sizing(FALSE)
    )
  )
})

observeEvent(input$state, {
  if (input$state != "All US") {
    updateRadioButtons(session, "view",
      choices = state_choices,
      selected = "Model",
      inline = TRUE
    )
  }
})

observeEvent(input$usmap_selected, {
  sel_map <- input$usmap_selected
  if (any(sel_map == state_list)) {
    updateSelectInput(session, "state", selected = sel_map)
  } else {
    sel_county <- us_hospitals |>
      filter(fips == sel_map)

    showModal(
      modalDialog(
        title = sel_county$county_name[1],
        sel_county |>
          arrange(city, facility_name) |>
          mutate(nbr = row_number()) |>
          select(nbr, facility_name, city) |>
          gt() |>
          cols_label(
            nbr = "",
            facility_name = md("**Hospital Name**"),
            city = md("**City**")
          ) |>
          tab_options(table.font.size = 14),
        easyClose = TRUE,
        fade = TRUE,
        size = "l"
      )
    )
  }
})

output$pop_plot <- renderGirafe({
  gp <- atc_plot_hospitals(input$pop)
  girafe(
    ggobj = gp,
    options = list(
      # width_svg = 10,
      # height_svg = 5,
      opts_selection(type = "single", only_shiny = FALSE),
      opts_tooltip(opacity = 0.7),
      opts_sizing(FALSE)
    )
  )
})

output$pop_plot_model <- renderGirafe({
  gp <- atc_plot_hospitals(show_model_results = TRUE)
  girafe(
    ggobj = gp,
    options = list(
      width_svg = 10,
      # height_svg = 5,
      opts_selection(type = "single", only_shiny = FALSE),
      opts_tooltip(opacity = 0.7),
      opts_sizing(FALSE)
    )
  )
})

observeEvent(
  input$us,
  {
    updateSelectInput(session, "state", selected = "All US")
    updateRadioButtons(session, "view", choices = us_choices, inline = TRUE)
  }
)
```

