---
title: "Access to Care"
author: "RStudio"
output: 
  powerpoint_presentation:
    reference_doc: template.potx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 9, fig.height = 7, fig.align = "center")

library(dplyr)
library(ggplot2)
library(pins)
library(connections)

if(Sys.getenv("R_CONFIG_ACTIVE") == "rsconnect") {
  boardname <- "rsconnect"
  board_register_rsconnect(
    server = Sys.getenv("connect_url"),
    key = Sys.getenv("connect_key")
    )
} else {
  boardname <- "local"
  board_register(boardname)  
}

model <- pin_get("atc-model", board = boardname)
states <- pin_get("atc-db-states", board = boardname) %>% collect()
county_hospitals <- pin_get("atc-db-base-map", boardname)
```

## County population vs hospitals

```{r}
county_hospitals %>%
  ggplot() +
  geom_point(aes(hospitals, population), color = "#E69F00", alpha = 0.5) +
  scale_y_continuous(breaks = 0:10 * 1000000, labels = paste0(0:10, "M")) +
  theme_minimal() 
```

---

## Model

```{r}
summary(model)
```

---

## Overlay the model


```{r}
bounds <- county_hospitals %>%
  summarise(
    mi = min(population, na.rm = TRUE), 
    mx = max(population, na.rm = TRUE)
    ) %>% 
  collect() %>%
  as.numeric()

preds <- predict(
  model, 
  data.frame(population = bounds),
  interval = "prediction"
  )

county_hospitals %>% 
  group_by(population, hospitals) %>%
  summarise() %>%
  ggplot() +
    geom_point(aes(hospitals, population), color = "#E69F00", alpha = 0.5) +
    scale_y_continuous(breaks = 0:10 * 1000000, labels = paste0(0:10, "M")) +
    geom_segment(x = preds[1,2], y = bounds[1], 
                 xend = preds[2,2], yend = bounds[2], 
                 color = "#009E73") +
    geom_segment(x = preds[1,3], y = bounds[1], 
                 xend = preds[2,3], yend = bounds[2], 
                 color = "#CC79A7") +
    theme_minimal()
```

