---
title: "Access to Hospital Care Dashboard"
runtime: shiny_prerendered
output:
  flexdashboard::flex_dashboard:
    logo: RStudio1.png
    navbar:
    - align: right
      href: https://solutions.rstudio.com/tour/access_to_care/
      title: About
    orientation: rows
    social:
    - linkedin
    - twitter
    - menu
    source_code: embed
    theme: lumen
---

```{r setup, include = FALSE}
library(flexdashboard)
library(accesstocare)
library(ggplot2)
library(ggiraph)
library(usmap)
library(dplyr)
library(shiny)
library(rlang)

state_list <- c("All US", us_states$state_name)

county_map <- usmap::us_map("county")
  
under <- "#CC79A7"
over <- "#0072B2"  #009E73
at_level <- "#008b00"
```


State Info
======================================================================


Row 
-----------------------------------------------------------------------

### Options


```{r}
selectInput(
  inputId = "state",
  label = "Select a State:",
  choices = state_list,
  selected = "All US", 
  selectize = FALSE
  )
```

### Population

```{r}
valueBoxOutput("population")
```

### Hospitals

```{r}
valueBoxOutput("hospitals")
```

### Counties

```{r}
valueBoxOutput("counties")
```

### Underserved Counties

```{r}
valueBoxOutput("underserved")
```

Row {data-height=1050}
-----------------------------------------------------------------------

###  Map

```{r}
actionButton(
  inputId = "us",
  label = "All US"
  )

radioButtons(
  inputId = "view",
  label = "Select a view:",
  choices = c("Hospitals per Capita", "No. of Hospitals", "Population"), 
  inline = TRUE
  )
```

```{r, fig.width=5, fig.height=5, eval = TRUE}
girafeOutput("usmap")
```

```{r, context = "server"}

observeEvent(input$usmap_selected, {
  sel_map <- input$usmap_selected
  if(any(sel_map == state_list)) {
    updateSelectInput(session, "state", selected = sel_map)
  } else {
    sel_county <- us_hospitals %>% 
      filter(fips == sel_map) 
    
    showModal(modalDialog(
      title = sel_county$county_name[1],
      paste0(sel_county$facility_name, collapse = "\n\n")
    ))
  }
})

observeEvent(
  input$us, 
  updateSelectInput(session, "state", selected = "All US")
  )

output$usmap <- renderGirafe({
  
  low_color <- "#eeeeee"
  high_color <- over
  x_width <- 20
  
  if(input$view == "Hospitals per Capita") {
    vr <- "per_person"
    low_color <- over
    high_color <- "#eeeeee"
  }  
  if(input$view == "Population") vr <- "population"
  if(input$view == "No. of Hospitals") vr <- "hospitals"
    
  if(input$state == "All US") {
    gp <- us_states %>% 
      mutate(
        pop = format_number(population),
        tooltip = paste0(state_name, "\nPopulation: ", pop, "\nHospitals: ", format_number(hospitals))
        ) %>% 
      mutate(fill = !! sym(vr)) %>% 
      select(state, state_name, fill, tooltip) %>% 
      inner_join(us_hex_polygons, by = "state") %>% 
      ggplot() +
      geom_polygon_interactive(
        aes(x, y, group = state, fill = fill, data_id = state_name, tooltip = tooltip), 
        color = "#333333"
        ) +
      geom_text_interactive(
        aes(x, y, label = state, data_id = state_name), size = 10, 
        data = us_hex_positions
        ) +
      scale_fill_gradient(low = low_color, high = high_color) +
      theme_void() +
      theme(legend.position = "none")
  } else {
    
    state_polygons <- county_map %>% 
      filter(full == input$state)
    
    x_width <- state_polygons %>% 
      summarise(
        max_x = max(x),
        min_x = min(x),
        max_y = max(y),
        min_y = min(y)
      ) %>% 
      mutate(
        x_size = max_x - min_x,
        y_size = max_y - min_y,
        xy = x_size/y_size * 10
      ) %>% 
      pull(xy)
    
    gp <- us_counties %>% 
      filter(state_name == input$state) %>% 
      select(fips, pred_status) %>% 
      right_join(state_polygons, by = "fips") %>% 
      ggplot() +
      geom_polygon_interactive(
        aes(x, y, group = group, fill = pred_status, data_id = fips), 
        color = "#333333"
        ) +
      scale_fill_manual(values = c(over, under, at_level), breaks = c("above", "below", "ok")) +
      theme_void() +
      theme(legend.position = "none")
      
  }
  
  girafe(
    ggobj = gp,
    width = x_width, height = 10,
    options = list(
      opts_selection(type = "single", only_shiny = FALSE),
      opts_tooltip(opacity = 0.7)
      )
    )  
})

sel_state <- reactive({
  if(input$state == "All US") {
    us_states
  } else {
    us_states %>% 
      filter(state_name == input$state) 
  }
})

sel_county <- reactive({
  if(input$state == "All US") {
    us_counties
  } else {
    us_counties %>% 
      filter(state_name == input$state) 
  }
})

output$population <- renderValueBox({
  sel_state() %>% 
    summarise(sum(population)) %>% 
    pull() %>%
    format_number() %>% 
    valueBox(icon="fa-user")
    })

output$hospitals <- renderValueBox({
  sel_state() %>%
    summarise(sum(hospitals)) %>%
    pull() %>% 
    format_number() %>% 
    valueBox(icon="fa-ambulance",color="#E69F00")
  })

output$counties <- renderValueBox({
  sel_county() %>%
    count() %>% 
    pull() %>% 
    format_number() %>% 
    valueBox(icon="fa-map-marker",color = over)
  })

output$underserved <- renderValueBox({
  sel_county() %>%
    filter(pred_status == "below") %>% 
    count() %>% 
    pull() %>% 
    valueBox(icon="fa-h-square", color = under)
  })
```

