---
title: "Access to Care"
params:
  state:
    choices: [Alabama, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, District of Columbia, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming]
    input: select
    label: 'State:'
    value: California
resource_files:
- template.potx
output:
  powerpoint_presentation:
    reference_doc: template.potx
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(accesstocare)
```

# `r params$state`

## Background

We are trying to determine which counties in **`r params$state`** have comparatively more access or less access to hospital care.

A **statistical model using data from across the country** is used to identify those counties that have more or less than the model expects the specific county to have.

## County Map

```{r, fig.width = 10, fig.height = 6}
atc_plot_state_map(state = params$state)
```



