---
title: "Access to Care Data Preparation"
output: html_document
---

```{r, include = FALSE}
library(dplyr)
library(readr)
library(haven)
library(rlang)
library(tidyr)
library(stringr)
library(purrr)
library(tigris)
library(fs)
library(haven)
library(usmap)
library(pins)
```


```{r}
library(dplyr)
library(readr)
library(haven)
library(rlang)
library(tidyr)
library(stringr)
library(purrr)
library(tigris)
library(fs)
library(haven)
library(usmap)
library(pins)

## Read SAS dataset
hospitals_raw <- haven::read_sas("data/Structural_Measures_-_Hospital.sas7bdat") 

## Prepare hospital data
hospitals <- hospitals_raw %>%
  rename_all(str_to_lower) %>%
  rename_all(str_replace_all, " ", "_") %>%
  select(provider_id, hospital_name, state, county_name, location) %>%
  group_by_all() %>%
  summarise() %>%
  ungroup() %>%
  separate(location, into = c("address", "location"), sep = "\\(") %>%
  mutate(location = str_remove(location, "\\)")) %>%
  separate(location, into = c("latitude", "longitude"), sep = ",") %>%
  mutate(
    longitude = as.numeric(longitude), latitude = as.numeric(latitude),
    county_key = str_remove_all(county_name, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint")
    )

## Prepare state data
states <- usmap::statepop %>%
  select(-fips) %>%
  select(state = abbr, full) %>%
  mutate(state_id = row_number()) %>%
  select(state_id, everything())

## Prepare location data
hospital_locations <- hospitals  %>%
  filter(!is.na(longitude)) %>%
  select(state, longitude, latitude) %>%
  mutate(state = as.factor(state)) %>%
  inner_join(states, by = "state")  %>%
  select(state_id,longitude, latitude)

population <- usmap::countypop %>%
  mutate(
    county_key = str_remove_all(county, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint")) %>%
  rename(
    population = pop_2015,
    state = abbr
  )

hospital_count <- hospitals %>%
  count(state, county_name) %>%
  filter(!is.na(county_name)) %>%
  mutate(
    county_key = str_remove_all(county_name, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st.", "saint")) %>%
  rename(hospitals = n)

state_hospitals <- population %>%
  left_join(hospital_count, by = c("state", "county_key")) %>%
  replace_na(list(hospitals = 0))
```


```{r}
## Fit model
set.seed(100)

hospital_sample <- state_hospitals %>%
  sample_frac(0.3)

model <- lm(hospitals ~ population, data = hospital_sample)

predictions <- predict(
  model, 
  newdata = state_hospitals, 
  interval = "prediction"
  ) %>%
  as_tibble() %>%
  mutate_all(round)

hospital_results <- state_hospitals %>%
  inner_join(states, by = "state") %>%
  bind_cols(predictions) %>%
  mutate(
    result = case_when(
      hospitals < lwr ~ -1,
      hospitals > upr ~ 1,
      TRUE ~ 0
      )
    ) %>%
  select(-county_name, -fips, -full, -state) 

## Build state shapes
get_state_shapes <- function(path = "data/shapes.rds") {
  ## Should only rebuild if running on a local computer
  if(Sys.getenv("R_CONFIG_ACTIVE") == "rsconnect")  {
    dir_create("shapes")
    all_paths <- path("shapes", state.abb, ext = "rds") %>%
      set_names(state.abb)
    exist <- file_exists(all_paths)
    county_paths <- all_paths[!exist]
    imap(
      county_paths,
      ~ counties(.y) %>%
        write_rds(.x)
    )
    select_row <- function(x, y) x %% y == 0
    extract_coordinates <- function(path, decimals = 2) {
      state_rds <- readRDS(path)
      state_rds@polygons %>%
        map(~ {
          map(
            .x@Polygons,
            ~ tibble(
              long = .x@coords[, 1],
              lat = .x@coords[, 2],
              rn = 1:length(.x@coords[, 1]),
              sel = select_row(rn, 20)
            )) %>% 
            set_names(paste0("s", seq_along(.x@Polygons))) %>%
            map_df(~.x, .id = "shape_id")}) %>%
        set_names(state_rds$NAME) %>%
        map_df(~.x, .id = "county") %>%
        filter(sel) %>%
        select(-rn, -sel) %>%
        mutate(step = row_number())
    }
    county_states <- map_dfr(
      all_paths,
      extract_coordinates,
      .id = "state"
    ) 
    shapes <- county_states %>%
      mutate(
        county_key = str_to_lower(county),
        county_key = str_remove_all(county_key, " "),
        county_key = str_replace_all(county_key, "st. ", "saint")
      ) %>%
      select(-county)
    readr::write_rds(shapes, path, compress = "gz")
    shapes
  } else {
    readr::read_rds(path)
  }
}

## Data Optimizations
state_shapes <- get_state_shapes()

county_hospitals_full <- state_shapes %>%
  count(state, county_key) %>%
  inner_join(states, by = "state") %>%
  inner_join(hospital_results, by = c("state_id", "county_key")) %>%
  mutate(county_id = row_number())

county_shapes <- county_hospitals_full %>%
  select(state, state_id, county_key, county_id) %>%
  inner_join(state_shapes, by = c("state", "county_key")) %>%
  ungroup() %>%
  mutate(shape_id = as.integer(str_remove(shape_id, "s"))) %>%
  select(-state, -county_key)  %>%
  select(state_id, county_id, shape_id, step, everything()) %>%
  arrange(county_id, shape_id, step)

county_hospitals <- county_hospitals_full %>%
  mutate(
    county = str_remove(county, "County"), 
    county = str_squish(county)
    ) %>%
  select(-county_key, -n, -full, -state) %>%
  select(county_id, everything()) 

state_full <- county_hospitals_full %>%
  group_by(state) %>%
  summarise(
    hospitals = sum(hospitals),
    population = sum(population),
    under = sum(ifelse(result == -1, 1, 0)),
    counties = n()
  ) %>%
  ungroup() %>%
  inner_join(states, by = "state")
  
```

```{r} 
base_map <-  state_full %>%
  select(state_id, full, state) %>%
  inner_join(county_hospitals, by = "state_id") %>%
  mutate(
    population_label = ifelse(
      population > 1000000, 
      paste0(as.integer(round(population / 1000000)), "M"),
      paste0(as.integer(round(population / 1000)), "K")
      ),
    popup = paste0(
      "<b>", county, "</b>", 
      "<br/>Population: ", population_label, 
      "<br/>Hospitals: ", as.integer(hospitals),
      "<br/>Expected: ", as.integer(fit)
      ), 
    color = case_when(
      result ==  0  ~ "#008b00",
      result ==  1  ~ "#0072B2",
      result == -1  ~ "#CC79A7"
    ),
    result = case_when(
      result ==  0  ~ "Acceptable",
      result ==  1  ~ "Above",
      result == -1  ~ "Under"
    )
    )
```

```{r}
county_table <- base_map %>%
  select(
    full,
    County = county,
    Population = population_label,
    Hospitals = hospitals,
    Expected = fit,
    `Model Result` = result
    ) 
```

```{r}
## Output - Register PINs inside RStudio Connect
if(Sys.getenv("R_CONFIG_ACTIVE") == "rsconnect") {
  boardname <- "rsconnect"
  board_register_rsconnect(
    server = Sys.getenv("connect_url"),
    key = Sys.getenv("connect_key")
    )
} else {
  boardname <- "local"
  board_register(boardname)  
}
```

```{r}
pin(
  state_full,
  "atc-all-states",
  boardname
)
if(nrow(pin_find("atc-all-states", board = boardname)) == 0) stop("pin was not recorded")
```

```{r}
pin(
  hospital_locations,
  "atc-hospitals",
  boardname
)
if(nrow(pin_find("atc-hospitals", board = boardname)) == 0) stop("pin was not recorded")
```

```{r}
pin(
  county_shapes,
  name = "atc-county-map",
  board = boardname
  )
if(nrow(pin_find("atc-county-map", board = boardname)) == 0) stop("pin was not recorded")
```

```{r}
pin(
  base_map,
  name = "atc-base-map",
  board = boardname
  )
if(nrow(pin_find("atc-base-map", board = boardname)) == 0) stop("pin was not recorded")
```

```{r}
pin(
  county_table,
  name = "atc-county-table",
  board = boardname
  )
if(nrow(pin_find("atc-county-table", board = boardname)) == 0) stop("pin was not recorded")
```
