---
title: "Access to care"
output: html_notebook
---

```{r}
library(tidyverse)
library(rlang)
library(leaflet)
```

```{r}
hospitals <- read_csv("../data/hospital_list.csv")
hospitals
```

```{r}
hospital_locations <- hospitals  %>%
  select(state, longitude, latitude)
write_rds(hospital_locations, "../data/hospital_locations.rds")
hospital_locations
```

```{r}
population <- usmap::countypop

hospital_count <- hospitals %>%
  count(state, original_county) 


state_hospitals <- population %>%
  left_join(hospital_count, by = c("abbr" = "state", "county" = "original_county")) %>%
  mutate(hospitals = ifelse(is.na(n), 0, n)) %>%
  select(
    fips, 
    state = abbr, 
    county, 
    population = pop_2015,
    hospitals
    )

state_hospitals
```




```{r}
set.seed(100)

hospital_sample <- state_hospitals %>%
  sample_frac(0.3)

hospital_sample
```

```{r}
model <- lm(hospitals ~ population, data = hospital_sample)
write_rds(model, "../data/model.rds")
summary(model)
```

```{r}
predictions <- predict(model, 
  newdata = state_hospitals, 
  interval = "prediction") %>%
  as_tibble() %>%
  mutate_all(round)

predictions
```

```{r}
hospital_results <- state_hospitals %>%
  bind_cols(predictions) %>%
  mutate(result = case_when(
    hospitals < lwr ~ -1,
    hospitals > upr ~ 1,
    TRUE ~ 0)) %>%
  mutate(
    county_key = str_remove_all(county, " County"),
    county_key = str_remove_all(county_key, " Parish"),
    county_key = str_remove_all(county_key, " city"),
    county_key = str_to_lower(county_key),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint"),
      )  

write_rds(hospital_results, "../data/hospitals.rds")

hospital_results 
```

## State map

```{r}
shapes <- read_rds("../data/shapes.rds") %>%
  mutate(
    county_key = str_to_lower(county),
    county_key = str_remove_all(county_key, " "),
    county_key = str_replace_all(county_key, "st. ", "saint")
  ) 

shapes 
```
```{r}
county_hospitals <- hospital_results  %>%
  select(- county) %>%
  left_join(shapes, by = c("state", "county_key")) %>%
  filter(state != "PR", state != "AK") %>%
  filter(!is.na(county))

write_rds(county_hospitals, "../data/county_hospitals.rds", compress = "gz")

county_hospitals
```

```{r}
library(fs)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds", "model.rds")) %>%
  file_copy("../flexdashboard", overwrite = TRUE)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../RMarkdown-html", overwrite = TRUE)

path("..","data", c("county_hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../RMarkdown-pdf", overwrite = TRUE)

path("..","data", c("model.rds", "hospitals.rds", "hospital_locations.rds")) %>%
  file_copy("../plumber-api", overwrite = TRUE)

```


```{r}
states <- county_hospitals %>%
  group_by(state) %>%
  summarise() %>%
  pull()

```


```{r}

under <- "#CC79A7"
over <- "#0072B2"
at_level <- "#008b00"
hospital_color <- "#F0E442"
st <- c("LA")
#st <- states
include <- c(-1, 1, 0)
add_hospitals <- 0

initial_map <- leaflet() %>%
  addProviderTiles(providers$CartoDB) %>%
  addLegend("bottomright", 
            color  = c(under,over ,at_level, hospital_color), 
            labels = c("Less hopitals than expected",
                       "More hospitals than expected", "Within Range", 
                       "Hospital Location"), 
            title  = "Legend",opacity = 0.5)

locations <- hospital_locations %>%
  filter(state %in% st) %>%
  select(longitude, latitude) %>%
  mutate_all(round, 3) %>%
  count(longitude, latitude) %>%
  mutate(popup = paste0("Hospitals: ", n))

counties <- county_hospitals %>% 
  filter(state %in% st,
         result %in% include) %>%
  mutate(popup = paste0("<b>", county, "</b>",
                        "<br/>Population: ", prettyNum(population, big.mark = ","), 
                        "<br/>Hospitals: ", hospitals,
                        "<br/>Expected: ", fit
                        )) %>%  
  mutate(color = case_when(
    result ==  0  ~ at_level,
    result ==  1  ~ over,
    result == -1  ~ under
  )) 

county_map <- counties %>%
  transpose() %>%
  map(~{
    county <- .x
     transpose(county$data)  %>%
       map(~list(
         data = .x$data, 
         color = county$color,
         popup = county$popup
         ))
    }) %>%
  flatten() %>%
  reduce(
    ~ addPolygons(.x, 
                  lng = .y$data$long, 
                  lat = .y$data$lat, 
                  color = .y$color, 
                  popup = .y$popup,
                  weight = 1, fillOpacity = 0.3), 
    .init = initial_map)  


if(add_hospitals == 1) {
  county_map <- county_map %>%
    addCircleMarkers(
      lng = locations$longitude, 
      lat = locations$latitude,
      radius = 1.5 *locations$n,
      popup = locations$popup,
      fillColor = hospital_color, color = "gray", 
      fillOpacity = 0.7,weight = 1)
  } 

county_map
  
```




























